### PR TITLE
Make compatible with kitspace.org

### PR DESCRIPTION
**Pull request by kasbah**
Hey, thought this would be a neat project to include over on [kitspace.org](https://kitspace.org). All that's required is to add a kitspace.yml pointing at the right BOM. If you are happy to add it, simply merge this and I'll put it up. The page will continue to update with this repo as you make changes (thought the delay can be up to 24hrs). 

Here is [a preview of what it will look like](http://add-cariboulite.preview.kitspace.org/boards/github.com/kitspace-forks/cariboulite/). The BOM could be improved a little, especially to add distributor numbers for the "Buy Parts" buttons to show up. I do have a project to help with that: [bom-builder](https://github.com/kitspace/bom-builder) ([more info](https://kitspace.org/bom-builder/)). If you would like free access to a hosted version of that, shoot me an email: kaspar@kitspace.org

### CODE REVIEW

**Comment by meexmachina** [comment]
Thanks a lot, I am making a few changes in the final revision board so I'll need a few more days to finalize it and update the final Gerber files and final BOM. As I understand, kitspace DB will be updated automatically with the new files as I update them? if not what steps should I take to have it up to date?

**Comment by meexmachina** [comment]
and another question - how do you manage the DRC? CaribouLite uses HDI process (microvias) and down to 3 mil routh / space. So for instance OSHpark is not qualified (if I'm not mistaken) to manufacture such a PCB. But it is still in the list of manufacturers...

**Comment by meexmachina** [comment]
The kitspace UI is amazing though. Its gerber viewer is fast and informative. I didn't find though a way to page between layers...

**Comment by kasbah** [comment]
It would keep updating, yes. Actually quicker than every 24hrs since I am just improving it.

Thanks for pointing out the design constraints. It's probably best to hold off on putting the page up as it may lead to wasted money. That's what I decided to do in https://github.com/gregdavill/OrangeCrab/pull/14#issuecomment-590130879. You can keep the kitspace.yaml though and once we can better determine constraints and match them to manufacturers we can put it up. 

The gerber viewer is very nice indeed. It's actually not a Kitspace thing but done by Mike Cousins under the Tracespace name: https://github.com/tracespace/tracespace/tree/main/apps/view I know you can hide layers but not sure about paging through them.

**Pull request merged**
