### PR TITLE
proper phase reversal, logging update and timeout limitation

### PR DESCRIPTION
**Pull request by konimaru**
This fixes an issue (I == Q) mentioned in at least two issue reports (#61, #70).

### CODE REVIEW

**Comment by hudouseko** [comment]
I can confirm as well that issue [https://github.com/cariboulabs/cariboulite/issues/70](url) is resolved with this patch

**Review by great9 — APPROVED** [review]
fixes issue #70

**Comment by benlamonica** [comment]
@great9 or @daviddawe1982, will you merge this please? I noticed this mirroring problem as well when I was using SDR++ and after merging this PR locally, it got rid of the mirroring and it works much better now. It would be good for other users to have this fix.

**Review by great9 — APPROVED** [review]

**Comment by great9** [comment]
David needs to approve and that is not going to happen

**Review by daviddawe1982 — APPROVED** [review]

**Review by meexmachina — APPROVED** [review]

**Pull request merged**
